include:
  - services/bazarr/docker-compose.yml
  - services/homarr/docker-compose.yml
  - services/lidarr/docker-compose.yml
  - services/plex/docker-compose.yml
  - services/portainer/docker-compose.yml
  - services/prowlarr/docker-compose.yml
  - services/qbittorrent/docker-compose.yml
  - services/radarr/docker-compose.yml
  - services/sonarr/docker-compose.yml
  - services/tautulli/docker-compose.yml
  - services/watchtower/docker-compose.yml


networks: 
  high-seas: 
    driver: bridge