services:
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    hostname: radarr.lan
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.lan`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    networks:
      - high-seas
    env_file:
      - ../../.env
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    ports:
      - '7878:7878'
    volumes:
      - '${HMS_DIR}/apps/radarr:/config'
      - '${HMS_DIR}/data/downloads:/mnt/downloads'
      - '${HMS_DIR}/data/media/movies:/mnt/media'
    restart: unless-stopped
