services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr.lan
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazaar.rule=Host(`bazaar.lan`)
    networks:
      - high-seas
    env_file:
      - ../../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 6767:6767
    volumes:
      - ${HMS_DIR}/apps/bazarr:/config
      - ${HMS_DIR}/data/media:/mnt/media
    restart: unless-stopped